### ISSUE TITLE
Out of memory error when loading some TAPs

### ISSUE THREAD

**Issue by markround** [spectrumero/spectranet#12]
Hi,

Not sure if this is the correct place to discuss this but anyway... I started this thread at the Spectrum Computing Forums: https://spectrumcomputing.co.uk/forums/viewtopic.php?f=6&t=4971 which outlines the problem. I have a Spectranet card with firmware R600 and can also re-create the problem with FUSE emulator.

The short version is that some TAP games give a "4 Out of memory" error when loading, but apparently only after I have made use of the Spectranet streams extension. A simple test-case is to mount `tnfs.markround.com` and the run the following:

```
10 %connect #4,"tnfs.markround.com",32768
20 print #4; "status"
30 %close #4
40 %tapein "/games/r/R-Type.tap"
50 load ""
```

This example is also saved as test.zx on my site, so you can test with `%load "/test.zx"`.

The loading screen and Poke? prompt will load, but then the next part will fail with "4 Out of memory, 10:2".

If I do not make use of the streams extension (omitting lines 10-30) then the game loads and runs correctly.

The BASIC file that it falls over on reads:

```
1 LOAD "r-t?" CODE: RANDOMIZE USR VAL "50350"
10 CLEAR VAL "23980" : RANDOMIZE USR VAL "28784"
```

Any ideas ?

**Comment by markround** [comment]
Update - I fixed the R-Type tap but the general "problem" if it can be called that is that after using streams, STKEND and PROG get pushed up by 67 bytes, so there's probably some other titles that exhibit the same issue when doing a very aggressive low CLEAR (more details in that forum thread) . I'll see if I can find any and update this. I guess the general question is: is this expected behaviour, and is there any way of pushing things back down/reclaiming this memory?

**Comment by spectrumero** [comment]
Add:

`35 %reclaim`

to the code snippet above. This will free the space used by channels and streams (which was allocated by the Spectrum ROM routine MAKE_ROOM)
