### ISSUE TITLE
Interrupt based recv? 

### ISSUE THREAD

**Issue by desertkun** [spectrumero/spectranet#14]
Hello. As z88dk has gained new tool, [z88dk-gdb](https://github.com/z88dk/z88dk/wiki/Tool-z88dk-gdb), I am exploring ways to implement an actual gdbserver for Spectranet that would bring hardware debugging to the next level.
I have sorted out most things, one, however, is still outstanding: how gdbserver can receive data (e. g., "please stop execution") from gdb while the program is being executed?
Can we think of something similar to settrap that would issue a NMI interrapt once new data shows up?
Or, a way to issue a NMI every second or so, or N instructions?

**Comment by spectrumero** [comment]
I think it would need a bigger CPLD to do this (at least a simple implementation), it's already pretty full, and an address watch would need at least 16 1-bit registers.

You could do it with the ZX Breakout (CPLD board) though, I tend to put an '144 on those which has a lot more registers.

**Comment by desertkun** [comment]
> It might be possible to squeeze something in that routes the W5100 /INT line to an NMI, though (that might be possible with a single bit register and combinatorial logic)

Yeah, this is pretty much all I want. Hope you have the time to investigate, or hint how can I do that. I am not familiar with CLPD development.

**Comment by desertkun** [comment]
I've found a way to circumvent my problem without an interrupt based recv.
