### ISSUE TITLE
Emulators don't support new firmware (R1002)

### ISSUE THREAD

**Issue by desertkun** [spectrumero/spectranet#26]
I believe this change https://github.com/spectrumero/spectranet/commit/cb63483cece1131fca2adece7ffe8e16f954974f#diff-c4d69be91aa48b4379991be3f6e00fcb619fc1109ac6fbb1a245766782a56b53R83 causes emulators to be not able to erase pages.

```
F_FlashIdentify:
	ld a,(v_flashid)
	cp 0
	jr nz, .skipIdentify ; skip identification if sysvar is non zero
	push bc
	ld bc, PAGEB
	ld a,5
	out (c),a	; flash A12-A15 bits to 5
	ld a, 0xAA	; unlock code 1
	ld (0x555), a	; unlock addr 1
	ld a,2
	out (c),a	; flash A12-A15 bits to 2
	ld a, 0x55	; unlock code 2
	ld (0xAAA), a	; unlock addr 2
	ld a,0
	out (c),a	; flash A12-A15 bits to 0
	ld a, 0x90	; ID code
	ld (0x555), a	; ID
    ld a, (0x0001)	; read device ID
    ld (v_flashid),a	; store device ID in SRAM
    ld (0x401F),a ; DEBUG
    ld a,0x55 ; DEBUG
    ld (0x411F),a ; DEBUG
    ld a, 0xF0	; reset code
	ld (0x0000),a	; reset flash
    ld a,(v_pgb)
    out (c),a	; restore page B
	pop bc
.skipIdentify:
```
I found it by doing a few hundreds of elaborate rollbacks until I found this is the change that causes it.

For example an online emulator https://speccytools.org/emu/?tnfs=vexed4.alioth.net will NOT install a new firmware (click play, then hit A then any key, see an error).

![image](https://github.com/spectrumero/spectranet/assets/1666014/52af51aa-8a82-4b06-a4da-82ce1e8cf7e3)

Question is what is going on in that code? [wiki](http://spectrum.alioth.net/doc/index.php/Using_flash_memory) only mention magic sequences for writing a byte/erasing a page, but no sequences for device identification.

So, is the correct sequence as follows?

```
1. 0xAA -> 0x555
2. 0x55 -> 0xAAA
3. 0x90 -> 0x555
4. device_id <- 0x0001
```

**Comment by desertkun** [comment]
@ZXGuesser would appreciate your input here

**Comment by desertkun** [comment]
Ideally, we should just play around with this code
```asm
F_FlashEraseSector:
	; preserve page to start the erase from in C
	ld c,a

	call F_FlashIdentify

	ld a,(v_flashid)	; load flash type
	ld b,4 ; erase four 4k sectors
	
	; this could potentially give a false positive if a ROM contains these values in the second byte
	; a more robust check would be to also test the manufacturer ID is 0xBF (SST)
	cp 0xB5	; SST39SF010A
	jr z, .eraseLoop
	cp 0xB6	; SST39SF020A
	jr z, .eraseLoop
	cp 0xB7	; SST39SF040
	jr z, .eraseLoop

	ld b,1 ; else erase one 16k sector
.eraseLoop:
```
in a way that emulators just keep working. There are emulators that are abandoned by their authors and getting them fix them is quite hard.

**Comment by desertkun** [comment]
Ok I found the reason, for some reason this change is using `0xAAA` unlock code instead of `0x2AA`, like documentation says. @ZXGuesser  Was it due to hardware changes and emulators now have to support `0xAAA` too or can we change the unlock codes back to `0x2AA`?

**Comment by ZXGuesser** [comment]
This is because the emulation was always missing an ID implementation.
I fixed this in fuse around the same time as making the changes in the spectranet firmware and it's been merged for the next release.

**Comment by desertkun** [comment]
That's good to know ... fuse is not dead? I had to make a fork because the PRs weren't getting merged in.
What about the documentation though, is it supposed to be aaa now?

**Comment by ZXGuesser** [comment]
The docs is all @spectrumero's department 🙂
It's all a bit confusing and convoluted because the datasheets for the chips are vague, and bits of the address come from the paging logic and so on.

https://sourceforge.net/p/fuse-emulator/fuse/ci/2effbd6d9c71419779372eeb13327e2f2013c9c2/

**Comment by desertkun** [comment]
Okay. How did you manage to merge something into fuse? I have like tons of stuff on my fork, including gdbserver support.

**Comment by ZXGuesser** [comment]
Just made a merge request thingy and forgot all about it for months until Sergio got around to merging it 😅
