### ISSUE TITLE
Cannot make it work from CP/M Plus

### ISSUE THREAD

**Issue by pawosm-arm** [spectrumero/spectranet#3]
Some time ago I have written a FID device driver for the CP/M Plus system that exposes Spectranet device's extra RAM as an M: ramdisk to the CP/M users (see [1]). It required some fiddling with memory layouts and paging, yet it worked nicely, even with Spectranet emulation in the FUSE emulator. Encouraged by this achievement, I wanted to write one more FID device driver exposing Spectranet as a character device (e.g. a serial port, similarly to WiFi device being exposed as a serial port on Spectrum Next). Unfortunately, I've stuck at some point and no one I've asked really knew what to do.

The first problem, CP/M Plus can be run only on ZX Spectrum 128k +3 model (or 128k +2A with Dandator device installed) and it uses extended +2A/+3 memory layouts (yes, I had to close the +2A/+3 jumper on the Spectranet board before I attached it). To boot CP/M one needs to start the machine in 128k mode and use the Loader from 128k mode startup menu. This cannot be done from 48k mode. The huge obstacle here is that with Spectranet attached, the machine always starts in 48k (USR 0) mode. I've learnt from ByteDelight that even if I close both of the 'disable' jumpers on the Spectranet board, the device is still there, I/O accessible and pagging-in/pagging-out should still work. I've verified that and it turned out to be the fact. That's how I came up with the spectramfid project (the Ramdisk FID driver for CP/M Plus). Unfortunately, no more functionalities than on-board RAM seem to respond.

Attached is the unfinished code of my attempt to implement a new driver, called `spectran.fid`. Although the exposed activity functions are left unimplemented with `TODO: implement` comment, the problem with which I have stuck affects much earlier stage and is situated in the `fidems` function responsible for this FID driver initialization. Those `INITHW`, `IFCONFIG_INET`, `IFCONFIG_NETMASK` functions that I'm trying to call, declared in the included https://github.com/spectrumero/spectranet/blob/master/include/spectranet.inc file, do not seem to do anything. Can someone look at my code and justify what am I doing wrong or what this code lacks?:
[spectran.asm.txt](https://github.com/spectrumero/spectranet/files/4575076/spectran.asm.txt)

Note that `hw_addr` in the attached file is fake (filled with ones). I've put the real MAC address of my Spectranet device there during my test runs.

[1]. https://sourceforge.net/projects/spectramfid

**Comment by ZXGuesser** [comment]
You can reset the spectrum back into the +3 menu after the spectranet has initialised, just set the paging registers to ROM 0 and jump to 0x0000.
I made a small program to do this that I load from my tnfs server, but if you don't want that requirement you could make a ROM module that installs a small basic extension to do the same, i.e. once booted run `%page` or something to soft reset into the +3 menu. You may even be able to make it boot straight into the +3 menu, since you don't care about all the BASIC integration being initialised.

**Comment by pawosm-arm** [comment]
Wow, that's an interesting hint, thanks @ZXGuesser! Can you quote your small program here before I make my (faulty?) attempt?

**Comment by ZXGuesser** [comment]
It's simply
`
xor a
ld bc,0x7ffd
out (c),a
ld b,0x1f
out (c),a
jp 0x0000
`
It should be easy to make a spectranet module that copies that to system RAM and executes it from a basic command too.

**Comment by pawosm-arm** [comment]
Thanks @ZXGuesser!

**Comment by ZXGuesser** [comment]
Obviously any spectranet features which interact with the BASIC interpreter won't work, so you might find other things break further along. I only use this as a way to get into +3 BASIC to do disk stuff without having to shut down and remove the spectranet each time, but I think I've used the arbitrary memory loading feature while in this state successfully in the past.

**Comment by pawosm-arm** [comment]
I wonder how much this Spectranet firmware relies on the ZX BASIC interpreter. My plan is to have it working, initially on CP/M, further on possibly on Fuzix with the simple goal of sending TCP packets back and forth. An userspace library (with functions talking to the FID driver responsible for accessing the Spectranet device) would be responsible for encapsulating particular requests and responses. The only thing this FID driver would be able to connect through the local network should be a custom TCP server running on a specified remote host that would do all of the heavy lifting of turning those requests into a proper network communication. This may seem like re-inventing SLIP protocol that encapsulates TCP/IP networking over humble serial port connection, yet the major benefit of doing so with Spectranet is that Spectranet isn't an RS232 serial port: I expect it to be (much) faster.

**Comment by pawosm-arm** [comment]
@ZXGuesser your bit of code works and indeed I can boot both CP/M Plus and Fuzix with all Spectranet functionalities enabled.

I also noticed that when I enable Spectranet itself but leafe RST-8 jumper at disabled position, +3 boots into 48k BASIC (USR 0) but the keyboard isn't working! I had to set both jumpers to enabled position in order to start the machine and type in the pokes (I placed your routine at 23296).

I guess I need to rewrite my FID driver. With the current code, all the network device diodes become dark as soon as my paging in routine is started - the TCP connection (at port 2424) with my PC isn't established.

**Comment by pawosm-arm** [comment]
Finally, I've found that it is possible to interact with it from CP/M booted according to your suggestion. I just had to remove all of the paging-in/paging-out code from my original driver as it is not needed anymore. It is sufficient to ensure FID driver with its buffers is in Bank 5, disable interrupts, set stack to use one of FID driver buffers and switch memory layout to traditional toastrack's memory layout. On the way back it is enough to return to CP/M-utilized +2A/+3 memory layout, restore remembered stack pointer, enable interrupts, and that's it, we're back in the CP/M world.

Eventually, I could create TCP socket (so the communication with Spectranet Firmware works), but that's about it. I could not connect any host in my local network on listened TCP ports. Turned out, my Spectranet device is likely to be broken.... I wonder at what level though, as I can `arping` it and the response comes from its MAC address. Still, none of the 48k BASIC examples from [1] worked for me, e.g. I could not connect to the `%listen` example, which is the definite proof that something is wrong with the device.

I guess this ticket can be closed, as a very basic interaction from CP/M was eventually established.

[1] http://spectrum.alioth.net/doc/index.php/Guide

**Comment by pawosm-arm** [comment]
BTW. Can those connect/send/recv functions be entered with interrupts disabled?!

**Comment by pawosm-arm** [comment]
Turned out, the MAC address was wrong and my programmable switch was filtering it out.

So there's only interrupts question above I'd like to be answered...

**Comment by pawosm-arm** [comment]
Moving forward, I can create socket, I can connect remote host but still I cannot send a byte:

```
    di
    ld (buff), a
    ld a, (socket)
    ld de, buff
    ld bc, 1
    ld hl, SEND
    call HLCALL
; should check 'carry' and BC here, but for now ignore both
    ei
```
Unfortunately, nothing appears on the other side and executing this code repeatedly result in spontaneous reset...

**Comment by pawosm-arm** [comment]
Even more of an update. I've copied the code above right after connection. It worked! A byte of data was received by the other side! I wonder if it is OK to create socket, open a connection and then go back to +3 memory layout for a while, then return to standard memory layout and send data to previously opened connection through previously created socket...

**Comment by pawosm-arm** [comment]
Finally I nailed it down and found out how to use it from CP/M. As I suspected, socket connection functions should not be entered with DI. This required a whole lot of trickery to hide CP/M from the normal 128k mode ISR (to prevent damage of the CP/M interior). It would be a subject for another story. Closing this ticket, as the topic is covered entirely.

**Comment by pawosm-arm** [comment]
Gents, I need to reopen this one. I've been focusing so much on protecting CP/M from Spectranet that I didn't spot the opposite problem: somehow CP/M can cause Spectranet's total crash. It happens only when I start larger userspace programs (e.g. dBase or DX-Forth).

CP/M's userspace runs always in an +3's offscreen memory layout consisting of 0,1,2,3 memory banks (so all of the text output to Bank 5's framebuffer is going through the kernel, I guess through a small buffer at the very end of Bank 3). Most of them programs use Bank 0 for code and Bank 3 for stack. Typical smaller programs don't even fill Bank 0 entirely (same with stack, most of the Bank 3 is left unused), so when I wrote memory dump program, I could still find original speccy's UDG at the end of Bank 0. Yet as soon as I start and quit a program that fills entire Bank 0 (and even beyond) and make heavy use of stack in Bank 3, any further attempt to make use of Spectranet routines (using trickery that otherwise proved to work) causes total crash.
Are those Spectranet's socket communication routines use Spectrum's RAM memory (namely, banks 0, 1, 2 or 3)? Is ist safe to refer (read, write, jump, call) the addresses  at the end of Bank 0 when it's in +3's special memory layout 0 (which is 0x0000-0x4000 area that includes trapped addresses 0x3ff*)?. Is Spectranet's trapping mechanism aware of +3's special memory layouts?

**Comment by pawosm-arm** [comment]
I managed to prepare smallest reproducer, it does not take much:

```
#include <string.h>
#include <unistd.h>

#define SPACE_SIZE 16384U

int main()
{
  char *space = sbrk(SPACE_SIZE);

  if (space)
    memset(space, 0xffU, SPACE_SIZE);
  return 0;
}
```
Subsequent use of Spectranet after running this, causes crash. For such a small program the heap starts in Bank 0, memset() writes at the end of Bank 0 and the beginning of Bank 1.

**Comment by pawosm-arm** [comment]
I narrowed above to the last 8 bytes of Bank 0. Apparently, any write attempt into there must have triggered a trap code and (due to an unexpected content of this part of memory) it must have done something bad (like making Spectranet believe it's none of the 128k machines).

I've looked into this repo and I think I've found the reason for the observed crash. It's in https://github.com/spectrumero/spectranet/blob/b2836e0c5e26aec95dcd59f8452e5f12b3a048c1/rom/save7ffd.asm#L85 - this code examines the contents of a byte at the address 8. In case of CP/M, this can be RAM Bank 0 (while in userspace) or RAM Bank 4 (while in kernel). Userspace programs start at 0x100 and there's zero at 0x08. When in kernel, it's part of RST0 handler, value may vary with CP/M versions. On the other end, the topmost 4kB of Bank 4 is the font area, I guess the last 8 bytes aren't used in the default configuration, hence I never observed crash caused by the kernel operation itself.

Current code https://github.com/spectrumero/spectranet/blob/b2836e0c5e26aec95dcd59f8452e5f12b3a048c1/rom/save7ffd.asm#L115 when it meets unknown content of a byte at the address 8 resets 128k flag (so I guess it makes Spectranet believe it's Spectrum 48k!) and sets carry flag (I guess it signals operation failure). IMO it's too drastic. CP/M keeps its own record of what was written into ports 7ffd and 1ffd, so I always revert to those recorded values when returning to +3 memory layout, Spectranet does not need to take care about it. I guess proper reaction of the trap handler should be to give up and return to normal Speccy's operation when unknown value is spotted at the address 8.

**Comment by pawosm-arm** [comment]
@ZXGuesser as I'm able to build firmware from this repo and reflash my spectranet device with it, I'd like to ask you, do you think it would be possible to disable trapping when in +3 memory layout modes (Bank 0 or Bank 4 in lowest addresses) just by modifying the firmware or does it require modifications in the hardware?

**Comment by ZXGuesser** [comment]
It's hardware (in the CPLD) except for the programmable trap

**Comment by spectrumero** [comment]
J2 disables all traps. Put a jumper on this when running CP/M.

**Comment by pawosm-arm** [comment]
Thanks for your replies. I'm sorry for spamming this ticket, I was posting here whenever I found something, even a small thing, hence it grew enormously.

@ZXGuesser, I was afraid it's like that.

@spectrumero, thing is, I want to use spectranet device from CP/M. For that reason I'm trying to develop a FID driver. So far I've managed to make sure the FID driver is always running in Bank 5 (along with all of the data exchange buffers and small stack), so (with interrupts disabled), I can leave +3 memory layout and switch to traditional 128k layout with Spectrum ROM at the lowest addresses. I also managed to make sure the +3 ROM's system variables are back at the right place of Bank 5, so I can safely re-enable interrupts while there. At that moment I need those spectranet traps to be working. I don't want them to interfere when I'm back in CP/M when there's either userspace (Bank 0) or kernel (Bank 4) at the lowest addresses. So the all-or-nothing approach (by means of placing or removing a jumper) is not what I'm looking for...

**Comment by spectrumero** [comment]
You can still use it with traps disabled - the memory can be paged in with OUT instructions instead of traps (it just means you'll probably want a routine in your driver that pages in the memory, makes the call, then pages it out - as without the traps the paging is no longer automatic). Bit 0 of the control and status register controls memory paging.

See http://spectrum.alioth.net/doc/index.php/Spectranet_CPLD#Control_and_Status_Register

This register is controlled by IO port 0x033b.

Once you've set the page-in bit, you can then use the entry points that are listed in jumptable.asm as normal, and then later unpage it when you're done by setting the page-in bit back to 0.

**Comment by pawosm-arm** [comment]
@spectrumero hey, that's more or less how my 'spectramfid' FID driver works (which exposes Spectranet extra RAM to CP/M as a block device, namely, an M: ramdisk). Trouble is, I couldn't manage to do much more than that, e.g. the network card seemed to be persistently uninitialized (maybe I didn't try hard enough and in the meantime it turned out the MAC address of the device was wrong and my 'intelligent' switch was dropping all of the network packets originated from spectranet, so I may not even notice the device was actually initialized). Meanwhile @ZXGuesser showed me a trick allowing me to boot CP/M with the traps enabled (and initialization done on the powerup), yet this caused problems with traps in +3 memory layouts. Overall, what I want to achieve seems doable, though I'm lacking some details. Namely, for my ramdisk driver I knew exactly which Spectranet pages (including Spectranet RAM pages) I want to page in, but to initialize the device and make actual use of it (e.g. set the MAC, set the IP, create a socket, open TCP connection, send TCP packet), I'm not sure which pages are relevant.

**Comment by spectrumero** [comment]
When you first start up, if you call J_reset it should do all the initialization stuff (or you could take the J_reset code from reset.asm and modify it and drop the bits you don't need). The actual location of J_reset is going to depend on the final assembled Spectranet ROM image so unfortunately it's not guaranteed to remain in the same place (but it almost certainly will - when it comes to the linking stage, reset.o is the next thing after zeropage.o, which is highly unlikely to change)

**Comment by pawosm-arm** [comment]
I've copied much of the `J_reset` routine (along with `F_initroms` function) into my FID driver initialization routine. When started, it brings the network device up, desktop machine can ping its IP address, TCP connection can be established from the FID driver, but that's about the end of the good news. Sad thing is that page out operation closes all of the TCP connections. And establishing one takes time. So it is essential to keep the TCP connection opened between the FID driver activities (namely, when it returns to +3 memory layouts). In effect, when my FID driver leaves 128k memory layout and goes back to previously used +3 memory layout, it does not page out Spectranet! It seems to work, until I try to start any bigger CP/M userspace program. Despite having both of the Spectranet's on-board 'Disable' jumpers closed, any write to the last eight bytes of the Bank 0 (while in +3 layout) ends with a crash, the same as with those jumpers opened and the device initialized by its own reset routine...
I guess it's time to give up :(

**Comment by spectrumero** [comment]
Can you reproduce it on the Fuse emulator?

If you can, then you've got a debugger you can use to step through code.

Also, sockets shouldn't ever be affected by paging operations (and definitely shouldn't close). It almost sounds like the device wasn't actually paged out and something wrote to the W5100's memory map.

**Comment by ZXGuesser** [comment]
You have to be careful testing things on Fuse because it doesn't simulate bus collisions from asserting the data bus while in special paging mode.

**Comment by pawosm-arm** [comment]
> Can you reproduce it on the Fuse emulator?

I've tried. Although the debugger shows Spectranet ROM is being paged in, and the static RAM pages behave like RAM, it seems like Spectranet ROM pages are empty! I guess there's a document somewhere describing how to make Spectranet emulation in Fuse fully operational.

> Also, sockets shouldn't ever be affected by paging operations (and definitely shouldn't close).

Wow, that's a strong reassurance. When I was doing my experiments, I was pinging Spectranet IP from my Desktop PC. About three pings returned when FID driver was initializing itself (and the Spectranet device), then they stopped, more or less about the time when CP/M reached fully operational userspace state. Subsequent attempt to write to the socket opened in FID init failed (no crash, just fail).

> It almost sounds like the device wasn't actually paged out and something wrote to the W5100's memory map.

At the moment I can't imagine how it could happen...

**Comment by pawosm-arm** [comment]
> Can you reproduce it on the Fuse emulator?

Seems I need to 'reflash' the Spectranet emulation, just like the real thing! Insane.

**Comment by pawosm-arm** [comment]
@spectrumero, @ZXGuesser thanks for your hints. I've managed to configure Spectranet in Fuse, all networking functionalities seem to work, except ICMP ping, as the emulated interface must be bound to the host machine local IP addresses (e.g. 127.0.0.1 can do) so pinging them is a pointless exercise.

Anyway, my code in my FID driver works in Fuse: page-out and subsequent page-in don't kill TCP connection, I can write to a socket and I can observe messages sent from Fuse on a custom TCP server I'm running on my PC. Now I wonder what's different. I've flashed the same firmware on both emulation and the real thing, so the difference seems to be purely in hardware...

**Comment by pawosm-arm** [comment]
Success! I was wondering how paging in/out code could behave different on Fuse comparing to the real thing and eventually I decided my code needs to be massively simplified. And it works now! on both Speccy and in Fuse.
Now page-in is just this:
```
    ld bc, CTRLREG
    in a, (c) ; read current state of the CPLD register before use
    and 0xf0 ; relevant bits only
    or 0x01 ; page-in request
    out (c), a ; page in
```
Page-out is even shorter:
```
    ld bc, CTRLREG ; CPLD register
    in a, (c) ; read current state of the CPLD register before use
    and 0xf0 ; relevant bits only
    out (c), a ; page out
```
Whole routines to switch between CP/M's FID and 128k mode with Spectraned paged-in look like this (both entered with interrupts disabled):
```
spectranet_layout_in_di:
; H - CP/M's original memory layout
; D - 128k's original memory layout
; returns:
; nothing
; corrupts:
; flags, A, BC
    pop bc
    ld (stack_ptr), sp
    ld sp, tmp_stack_top ; a small stack in Bank 5
    push bc
    ld a, h
    and 0x08 ; keep motor state (bit 3)
    or 0x04 ; normal paging mode with +3DOS/48BASIC in ROM (bit 2)
    ld bc, 0x1ffd ; +2A/+3 register
    out (c), a ; quit special memory layouts
    ; we're still in Bank 5
    ld bc, CTRLREG ; CPLD register
    in a, (c) ; read current state of the CPLD register before use
    and 0xf0 ; relevant bits only
    or 0x01 ; page-in request
    out (c), a ; page in
    ret
;
spectranet_layout_out_di:
; H - CP/M's original memory layout
; D - 128k's original memory layout
; returns:
; nothing
; corrupts:
; A, BC
    ld bc, CTRLREG ; CPLD register
    in a, (c) ; read current state of the CPLD register before use
    and 0xf0 ; relevant bits only
    out (c), a ; page out
    ld bc, 0x7ffd ; 128k register
    out (c), d ; revert to original state of 128k's memory layout
    ld bc, 0x1ffd ; +2A/+3 register
    out (c), h ; switch back to CP/M's memory layout
    pop bc
    ld sp, (stack_ptr)
    push bc
    ret
;
```
After that, SP is changed further to point at NMISTACK, interrupts are enabled and socket library functions are called. Example code invoking the above (entered with interrupts enabled):
```
    ld a, (SVC_BANK_05)
    ld d, a
    ld a, (SVC_BANK_68)
    ld h, a
    call spectranet_layout_in_di ; corrupts flags, A, BC; returns nothing
    push bc
    push de
    push hl
    ld (stack_ptr2), sp
    ld sp, NMISTACK
    ei
_fiddwrite_send_loop:
    ld a, (socket)
    ld de, buff
    ld bc, 1
    call SEND ; corrupts flags; returns in carry flag, A, BC
    jr c, _fiddwrite_send_finish
    ld a, c
    cp 1
    jr nz, _fiddwrite_send_loop
_fiddwrite_send_finish:
    di
    ld sp, (stack_ptr2)
    pop hl
    pop de
    pop bc
    call spectranet_layout_out_di ; corrupts A, BC; returns nothing
    call SVC_CATCHUP ; corrupts flags, A, BC, DE, HL; returns nothing
```
I guess now this ticket can be closed for good!

**Comment by spectrumero** [comment]
Excellent :-) If you want to add it to this repo don't forget to send a pull request :-)
